networks:
  redis-network:
    driver: bridge
services:
  redis:
    container_name: redis-standalone
    image: redis:alpine
    networks:
    - redis-network
    ports:
    - 6379:6379
version: '2.2'
volumes:
  redis-data:
    driver: local
